name: CI Pipeline
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker gcr.io --quiet

      - name: Build and push Docker image
        env:
          GCR_HOSTNAME: gcr.io
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          docker build -t ${GCR_HOSTNAME}/${GCP_PROJECT_ID}/hello-world:${{ github.sha }} .
          docker push ${GCR_HOSTNAME}/${GCP_PROJECT_ID}/hello-world:${{ github.sha }}
          docker tag ${GCR_HOSTNAME}/${GCP_PROJECT_ID}/hello-world:${{ github.sha }} ${GCR_HOSTNAME}/${GCP_PROJECT_ID}/hello-world:latest
          docker push ${GCR_HOSTNAME}/${GCP_PROJECT_ID}/hello-world:latest
