name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: gentle-dominion-245803
      IMAGE: hello-world

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker to use the gcloud command-line tool as a credential helper
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }} .

    - name: Push Docker image to Google Container Registry
      run: |
        docker push gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }}

    - name: Update deployment.yaml
      run: |
        sed -i "s|gcr.io/${GCP_PROJECT_ID}/${IMAGE}:latest|gcr.io/${GCP_PROJECT_ID}/${IMAGE}:${{ github.sha }}|" kubernetes/deployment.yaml
        sed -i "s|\${GCP_PROJECT_ID}|${GCP_PROJECT_ID}|g" kubernetes/deployment.yaml
        sed -i "s|\${IMAGE}|${IMAGE}|g" kubernetes/deployment.yaml
        sed -i "s|\${IMAGE_TAG}|${{ github.sha }}|g" kubernetes/deployment.yaml

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials hello-world-cluster-tokyo --zone asia-northeast1-a --project ${{ env.GCP_PROJECT_ID }}
        kubectl apply -f kubernetes/deployment.yaml
        kubectl rollout status deployment/hello-world

    - name: Verify Deployment
      run: |
        kubectl get services -o wide
