name: CI/CD Pipeline
on: [push, pull_request]

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: hello-world-cluster-tokyo
  GKE_ZONE: asia-northeast1-a
  IMAGE: hello-world

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'docker-credential-gcr'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker gcr.io --quiet

      - name: Build and push Docker image
        env:
          GCR_HOSTNAME: gcr.io
        run: |
          docker build -t ${GCR_HOSTNAME}/${GCP_PROJECT_ID}/${IMAGE}:${{ github.sha }} .
          docker push ${GCR_HOSTNAME}/${GCP_PROJECT_ID}/${IMAGE}:${{ github.sha }}
          docker tag ${GCR_HOSTNAME}/${GCP_PROJECT_ID}/${IMAGE}:${{ github.sha }} ${GCR_HOSTNAME}/${GCP_PROJECT_ID}/${IMAGE}:latest
          docker push ${GCR_HOSTNAME}/${GCP_PROJECT_ID}/${IMAGE}:latest

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Verify Project ID
        run: |
          DEPLOYMENT_PROJECT_ID=$(grep -oP 'gcr.io/\K[^/]+' kubernetes/deployment.yaml)
          if [ "$DEPLOYMENT_PROJECT_ID" != "$GCP_PROJECT_ID" ]; then
            echo "Warning: Project ID in deployment.yaml ($DEPLOYMENT_PROJECT_ID) does not match GCP_PROJECT_ID ($GCP_PROJECT_ID)"
            exit 1
          fi

      - name: Update deployment.yaml
        run: |
          sed -i "s|gcr.io/gentle-dominion-245803/hello-world:latest|gcr.io/${GCP_PROJECT_ID}/${IMAGE}:${{ github.sha }}|" kubernetes/deployment.yaml
          sed -i "s|\${GCP_PROJECT_ID}|$GCP_PROJECT_ID|g" kubernetes/deployment.yaml
          sed -i "s|\${IMAGE}|$IMAGE|g" kubernetes/deployment.yaml

      - name: Deploy to GKE
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          IMAGE_NAME: hello-world
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Apply the Kubernetes manifests
          kubectl apply -f kubernetes/deployment.yaml
      
          # Wait for the deployment to complete
          kubectl rollout status deployment/hello-world
      
          # Display information about the services
          kubectl get services -o wide
      
          # Optionally, display information about the pods
          kubectl get pods -l app=hello-world
