name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t hello-world:${{ github.sha }} .
          docker tag hello-world:${{ github.sha }} gcr.io/$GCP_PROJECT_ID/hello-world:${{ github.sha }}

      - name: Login to Google Container Registry
        run: echo ${{ secrets.GCP_SA_KEY }} | docker login -u _json_key --password-stdin https://gcr.io

      - name: Push Docker image
        run: |
          docker push gcr.io/$GCP_PROJECT_ID/hello-world:${{ github.sha }}
